(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>x==null||!Number.isFinite(Number(x))?'—':Number(x).toFixed(1);
const err=r=>r.error!=null&&Number.isFinite(Number(r.error))?Number(r.error):Number(r.actualPir)-Number(r.basePir);
const current=(r,id)=>r.eligible===true&&r.modelId===id;
function select(rows,state,id){return rows.filter(r=>(!state.round||String(r.round)===String(state.round))&&(state.source==='all'||(state.source==='current'?current(r,id):!current(r,id)))&&(!state.search||`${r.name} ${r.team} ${r.opponent}`.toLowerCase().includes(state.search.toLowerCase()))&&(state.result==='all'||(state.result==='hit'?Math.abs(err(r))<=5:Math.abs(err(r))>5))).slice().sort((a,b)=>state.sort==='error'?Math.abs(err(b))-Math.abs(err(a)):Date.parse(b.start)-Date.parse(a.start)||String(a.name).localeCompare(String(b.name)));}
function metrics(rows){return {n:rows.length,mae:rows.length?rows.reduce((s,r)=>s+Math.abs(err(r)),0)/rows.length:null,hit:rows.length?rows.filter(r=>Math.abs(err(r))<=5).length/rows.length*100:null};}
const date=s=>{const d=new Date(s);return Number.isFinite(d.getTime())?d.toLocaleString('he-IL',{timeZone:'Asia/Jerusalem',day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}):'לא זמין';};
const reason={minutes:'פער בדקות',efficiency:'פער בביצועים לדקה',availability:'שיחק למרות תחזית לאפס דקות','did-not-play':'לא שיחק למרות תחזית לדקות'};
const size=5;
function card(r,id){const error=err(r),hit=Math.abs(error)<=5,stats=r.actualStats||{};
return `<article class="ac-row"><div class="ac-rowhead"><div><b>${esc(r.name)}</b><small>${esc(r.team)} מול ${esc(r.opponent)} · ${r.home===true?'בית':r.home===false?'חוץ':'מיקום לא זמין'} · מחזור ${esc(r.round)}</small></div><span class="ac-badge ${hit?'hit':'miss'}">${hit?'בטווח ±5':'פער מעל 5'}</span></div><div class="ac-values"><span>צפוי <b>${n(r.basePir)}</b></span><span>בפועל <b>${n(r.actualPir)}</b></span><span class="${hit?'hit':'miss'}">פער <b dir="ltr">${error>0?'+':''}${n(error)}</b></span></div><details><summary>פירוט הבדיקה</summary><p>${current(r,id)?'תחזית מהגרסה הנוכחית':r.eligible?'תחזית אתר מגרסה קודמת':'תחזית בדיקה ישנה'} · משחק ${date(r.start)}</p><p>דקות: ${n(r.baseMinutes)} צפויות / ${n(r.actualMinutes)} בפועל.<br>${esc(reason[r.reason]||'אין פירוק זמין')} · תרומת הדקות: ${n(r.minutesContribution)} PIR · תרומת הביצועים: ${n(r.efficiencyContribution)} PIR.</p><p>נקודות ${n(stats.points)} · ריבאונדים ${n(stats.totalRebounds)} · אסיסטים ${n(stats.assistances)} · איבודים ${n(stats.turnovers)} · עבירות ${n(stats.foulsCommited)}.</p><small>הפער הוא תוצאה פחות תחזית. הפירוק חשבוני ואינו מוכיח מה גרם לפער.</small></details></article>`;}
function install(data){
const host=document.getElementById('learningReport');if(!host)return;
const heading=document.querySelector('#learning h2');if(heading)heading.textContent='בדיקת תחזיות · תמונת מצב';
const intro=document.querySelector('#learning > .card > p');if(intro)intro.textContent='תוצאות שנבדקו מול תחזיות שנשמרו לפני המשחק.';
if(!data||data.schema!=='learning-v1'||data.season!=='E2026'){host.innerHTML='<p class="notice">אין דוח בדיקה זמין לעונה הנוכחית.</p>';return;}
const rows=data.rows||data.largestMisses||[],id=window.__learningModelId||data.modelId,currentRows=rows.filter(r=>current(r,id)),rounds=[...new Set(rows.map(r=>r.round))].sort((a,b)=>b-a);
const defaultRows=currentRows.length?currentRows:rows,latest=defaultRows.length?Math.max(...defaultRows.map(r=>Number(r.round)).filter(Number.isFinite)):'';
const state={round:String(latest||''),source:currentRows.length?'current':'old',search:'',result:'all',sort:'date',page:0,view:'players'};
const active=!!(data.active&&data.modelId===id&&data.validation?.active&&data.validation.n>=60&&data.validation.games>=6),updated=Date.parse(data.updated_at),stale=Number.isFinite(updated)&&Date.now()-updated>2*3600000;
host.classList.add('audit-compact');
host.innerHTML=`<div class="ac-status"><b>${currentRows.length?`${currentRows.length} בדיקות מהגרסה הנוכחית`:'הגרסה הנוכחית עדיין ללא תוצאות בדיקה'}</b><span>${active?'תיקון אוטומטי מאומת פעיל':'התיקון האוטומטי עדיין לא פעיל'}</span><small>עדכון הדוח: ${date(data.updated_at)}${stale?' · הדוח לא עודכן בשעתיים האחרונות':''}. ${rows.length-currentRows.length} בדיקות בארכיון הגרסאות.</small></div><div class="ac-tabs"><button type="button" data-ac-view="players" aria-pressed="true">שחקנים</button><button type="button" data-ac-view="teams" aria-pressed="false">קבוצות</button></div><div id="acPlayers"><div class="ac-filters"><input id="acSearch" aria-label="חיפוש שחקן או קבוצה" placeholder="שחקן או קבוצה"><select id="acRound" aria-label="מחזור"><option value="">כל המחזורים</option>${rounds.map(r=>`<option value="${esc(r)}" ${String(r)===state.round?'selected':''}>מחזור ${esc(r)}</option>`).join('')}</select><select id="acSource" aria-label="גרסת תחזית"><option value="current" ${state.source==='current'?'selected':''}>הגרסה הנוכחית (${currentRows.length})</option><option value="old" ${state.source==='old'?'selected':''}>ארכיון גרסאות</option><option value="all">כל הגרסאות</option></select><select id="acResult" aria-label="תוצאה"><option value="all">כל התוצאות</option><option value="miss">פער מעל 5 PIR</option><option value="hit">בטווח ±5 PIR</option></select><select id="acSort" aria-label="סדר"><option value="date">המשחקים האחרונים</option><option value="error">הפערים הגדולים</option></select></div><p id="acScope" class="ac-scope"></p><div id="acMetrics" class="ac-metrics"></div><div id="acRows"></div></div><div id="acTeams" hidden></div><nav class="ac-pages" aria-label="עמודי תוצאות"><button type="button" id="acPrev">הקודם</button><span id="acPage"></span><button type="button" id="acNext">הבא</button></nav><details class="ac-method"><summary>מה נבדק ומה האלגוריתם למד?</summary><p>טווח ±5 PIR הוא סף התצוגה לבדיקת הדיוק. סיכום הארכיון מתייחס לגרסאות עבר ואינו מודד את הגרסה הנוכחית.</p><p>התיקון מכייל דקות ו־PIR לדקה לפי עמדה. הוא מופעל רק אחרי 60 תחזיות בשישה משחקי בדיקה ושיפור של יותר מ־2%.</p><p>בדיקת תיקון: ${data.validation?.n||0} תחזיות, ${data.validation?.games||0} משחקים. טעות לפני ${n(data.validation?.baselineMae)}, אחרי ${n(data.validation?.candidateMae)} PIR.</p></details>`;
function draw(){
const selected=select(rows,state,id),teams=(data.teamAudit?.games||[]).slice().sort((a,b)=>Date.parse(b.start)-Date.parse(a.start)),list=state.view==='teams'?teams:selected,count=list.length,pages=Math.max(1,Math.ceil(count/size));state.page=Math.min(state.page,pages-1);
document.getElementById('acPlayers').hidden=state.view!=='players';document.getElementById('acTeams').hidden=state.view!=='teams';
const m=metrics(selected);document.getElementById('acScope').textContent=`${state.source==='current'?'בדיקות מהגרסה הנוכחית':state.source==='old'?'ארכיון — תחזיות מגרסאות קודמות':'כל הגרסאות יחד'} · ${state.round?'מחזור '+state.round:'כל המחזורים'} · ${selected.length} תוצאות. הסיכום מחושב לפי המסננים.`;
document.getElementById('acMetrics').innerHTML=`<div><b>${m.n}</b><span>בדיקות</span></div><div><b>${n(m.mae)}</b><span>טעות PIR ממוצעת</span></div><div><b>${m.hit===null?'—':Math.round(m.hit)+'%'}</b><span>בטווח ±5</span></div>`;
document.getElementById('acRows').innerHTML=selected.slice(state.page*size,(state.page+1)*size).map(r=>card(r,id)).join('')||`<p class="notice">${state.source==='current'?'אין עדיין תוצאות לגרסה הנוכחית במסנן שנבחר. תחזיות חדשות ייבדקו לאחר שהמשחקים יסתיימו.':'אין תוצאות במסנן שנבחר.'}</p>`;
document.getElementById('acTeams').innerHTML=`<p class="ac-scope">רק תחזיות שנשמרו לפני משחק שהסתיים · ${teams.length} משחקים בארכיון. גרסת מודל לא נשמרה בבדיקות אלו; הן אינן מדד לגרסה הנוכחית.</p>`+teams.slice(state.page*size,(state.page+1)*size).map(g=>`<article class="ac-row"><div class="ac-rowhead"><b>${esc(g.home)} מול ${esc(g.away)}</b><span class="ac-badge ${g.winnerHit?'hit':'miss'}">${g.winnerHit?'המנצחת זוהתה':'המנצחת לא זוהתה'}</span></div><p>מחזור ${esc(g.round)} · ${date(g.start)} · תוצאה <b dir="ltr">${esc(g.homeScore)}–${esc(g.awayScore)}</b></p><details><summary>השוואת תחזית לתוצאה</summary><p>הפרש בית: ${n(g.forecast?.margin)} צפוי / ${n(g.actualMargin)} בפועל.<br>טוטאל: ${n(g.forecast?.total)} צפוי / ${n(g.actualTotal)} בפועל.<br>סיכוי לניצחון בית: ${n((g.forecast?.winProb??NaN)*100)}%.</p></details></article>`).join('')+(!teams.length?'<p class="notice">אין עדיין תחזיות קבוצות מוקדמות למשחקים שהסתיימו.</p>':'');
document.getElementById('acPage').textContent=count?`${state.page+1} / ${pages} · ${state.page*size+1}–${Math.min((state.page+1)*size,count)} מתוך ${count}`:'0 תוצאות';document.getElementById('acPrev').disabled=state.page===0;document.getElementById('acNext').disabled=state.page>=pages-1;
}
for(const [element,key] of [['acSearch','search'],['acRound','round'],['acSource','source'],['acResult','result'],['acSort','sort']])document.getElementById(element).addEventListener(element==='acSearch'?'input':'change',event=>{state[key]=event.target.value;state.page=0;draw();});
for(const direction of ['Prev','Next'])document.getElementById('ac'+direction).onclick=()=>{state.page+=direction==='Next'?1:-1;draw();};
host.querySelectorAll('[data-ac-view]').forEach(button=>{button.onclick=()=>{state.view=button.dataset.acView;state.page=0;host.querySelectorAll('[data-ac-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));draw();};});draw();
}
window.AuditCompact={select,metrics,current,card,install};
let attempts=0;function ready(){if(window.__learningReady){install(window.__learningReport);return;}if(++attempts>=320){install(window.__learningReport);return;}setTimeout(ready,150);}ready();
})();
