const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const sandbox={window:{},setTimeout(){},Date,console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('audit-compact.js','utf8'),sandbox);
const ui=sandbox.window.AuditCompact;
const rows=[{name:'Old round',round:3,start:'2026-10-03',eligible:true,modelId:'old',error:26,actualPir:40,basePir:14},{name:'Current',round:4,start:'2026-10-09',eligible:true,modelId:'new',error:2,actualPir:20,basePir:18},{name:'Archived site',round:4,start:'2026-10-08',eligible:true,modelId:'old',error:-10,actualPir:5,basePir:15},{name:'Legacy',round:4,start:'2026-10-07',eligible:false,modelId:'new',error:0,actualPir:8,basePir:8}];
const state={round:'4',source:'old',search:'',result:'all',sort:'date'};
let selected=ui.select(rows,state,'new');assert.deepEqual(Array.from(selected,r=>r.name),['Archived site','Legacy']);
assert.equal(ui.metrics(selected).n,2);assert.equal(ui.metrics(selected).mae,5);assert.equal(ui.metrics(selected).hit,50);
state.source='current';assert.equal(ui.select(rows,state,'new').length,1);
state.source='all';state.result='miss';assert.equal(ui.select(rows,state,'new').length,1);
state.round='';state.sort='error';assert.equal(ui.select(rows,state,'new')[0].name,'Old round');
assert.equal(ui.current(rows[3],'new'),false);assert.equal(ui.metrics([]).mae,null);
let html=ui.card({...rows[0],team:'<img>',opponent:'Rival',home:false,baseMinutes:20,actualMinutes:25},'new');assert(html.includes('&lt;img&gt;'));assert(html.includes('תחזית אתר מגרסה קודמת'));assert(html.includes('<details>'));assert(!html.includes('<details open'));
assert.equal(ui.metrics([{basePir:12,actualPir:15,error:null}]).mae,3);
const elements={};for(const id of ['learningReport','acPlayers','acTeams','acScope','acMetrics','acRows','acPage','acPrev','acNext','acSearch','acRound','acSource','acResult','acSort'])elements[id]={innerHTML:'',classList:{add(){}},querySelectorAll(){return []},addEventListener(type,fn){this.listener=fn;}};
sandbox.document={getElementById:id=>elements[id],querySelector(){return null;}};
sandbox.window.__learningModelId='new';
const archive=Array.from({length:13},(_,i)=>({...rows[2],name:'Player '+i}));
ui.install({schema:'learning-v1',season:'E2026',modelId:'new',updated_at:'2026-10-10T14:20:21Z',rows:archive.concat(rows[0]),validation:{}});
assert(elements.learningReport.innerHTML.includes('הגרסה הנוכחית עדיין ללא תוצאות בדיקה'));
assert(elements.acScope.textContent.includes('מחזור 4'));
assert.equal((elements.acRows.innerHTML.match(/<article /g)||[]).length,5);
elements.acNext.onclick();assert(elements.acPage.textContent.includes('2 / 3'));assert.equal((elements.acRows.innerHTML.match(/<article /g)||[]).length,5);
elements.acSource.listener({target:{value:'current'}});assert(elements.acRows.innerHTML.includes('אין עדיין תוצאות'));assert(elements.acNext.disabled);
console.log('PASS: latest-round filtering, strict model separation, filtered summary, sorting, empty sample, escaped compact cards, collapsed detail and five-row pagination');
