from pathlib import Path
p=Path('index.html');s=p.read_text()
helper='// Load individual games from the same current-season feed as the summary.\nconst lastThreeRequests = new Map();\nfunction lastThreeFetch(path){\n  if(!lastThreeRequests.has(path)) lastThreeRequests.set(path,fetch(path).then(r=>{if(!r.ok)throw new Error("game data unavailable");return r.json()}).catch(e=>{lastThreeRequests.delete(path);throw e}));\n  return lastThreeRequests.get(path);\n}\nfunction lastThreeName(name){return normName(name).split(/\\s+/).filter(Boolean).sort().join(" ")}\nasync function fillLastThreeGames(name,card){\n  try{\n    const data=await lastThreeFetch(\'./data/euroleague-live-E2026.json\');\n    if(data.season!==\'E2026\')throw new Error(\'wrong season\');\n    const key=lastThreeName(name);\n    const games=Object.values(data.games||{}).flatMap(g=>(g.rows||[])\n      .filter(r=>r.season===\'E2026\'&&lastThreeName(r.name)===key&&Number(r.minutes)>0)\n      .map(r=>({...r,date:r.date||g.date,gameCode:r.gameCode||g.gameCode})))\n      .sort((a,b)=>String(b.date||\'\').localeCompare(String(a.date||\'\'))||Number(b.gameCode)-Number(a.gameCode));\n    const unique=games.filter((g,i,a)=>a.findIndex(v=>v.gameCode===g.gameCode)===i).slice(0,3);\n    const rows=await Promise.all(unique.map(async g=>{\n      let opponent=\'—\';\n      try{\n        const box=await lastThreeFetch(`./data/backtest/cache/E2026-${Number(g.gameCode)}-stats.json`);\n        const side=[\'local\',\'road\'].find(side=>(box[side]?.players||[]).some(r=>lastThreeName(r.player?.person?.name)===key));\n        if(side){const other=box[side===\'local\'?\'road\':\'local\'];const club=other?.players?.find(r=>r.player?.club)?.player.club;opponent=club?.abbreviatedName||club?.name||\'—\';}\n      }catch(e){console.warn(\'Opponent unavailable\',g.gameCode)}\n      const date=String(g.date||\'\').slice(0,10).split(\'-\').reverse().slice(0,2).join(\'/\');\n      const value=v=>v==null||!Number.isFinite(Number(v))?\'—\':Number(v).toFixed(1);\n      return `<tr><td>${esc(opponent)}<small class="gameDate">${esc(date)}</small></td><td>${value(g.pir)}</td><td>${value(g.minutes)}</td></tr>`;\n    }));\n    if(!card.isConnected)return;\n    card.innerHTML=\'<h4>3 המשחקים האחרונים</h4>\'+(rows.length?`<table class="lastThreeTable" aria-label="שלושת המשחקים האחרונים"><thead><tr><th>יריבה</th><th>PIR</th><th>דקות</th></tr></thead><tbody>${rows.join(\'\')}</tbody></table>`:\'<p class="muted">אין עדיין משחקים ששוחקו בעונת 2026/27.</p>\');\n  }catch(e){if(card.isConnected)card.innerHTML=\'<h4>3 המשחקים האחרונים</h4><p class="muted">נתוני המשחקים לא זמינים כרגע. פתח שוב כדי לנסות מחדש.</p>\';}\n}\n'
css='.lastThreeCard{padding:10px!important;align-self:stretch}.playerSection .lastThreeCard h4{font-size:12px;margin:0 0 8px;color:var(--blue)}\n.lastThreeTable{width:100%;min-width:0;table-layout:fixed;border-collapse:collapse}.lastThreeTable th,.lastThreeTable td{padding:6px 3px;font-size:11px;border-bottom:1px solid var(--line);background:transparent;position:static}\n.lastThreeTable th:first-child{width:54%}.lastThreeTable th:not(:first-child),.lastThreeTable td:not(:first-child){text-align:center;direction:ltr;font-variant-numeric:tabular-nums}.lastThreeTable td:first-child{overflow-wrap:anywhere}.lastThreeTable tr:last-child td{border-bottom:0}.playerSection .lastThreeCard .gameDate{display:block;font-size:9px;margin-top:2px}.lastThreeCard .muted{font-size:11px;margin:0}\n'
if 'const lastThreeRequests' not in s:
    anchor='window.showPlayer=function(name){'
    metric='actualMetric("משחקים בעונה",recent.currentSeasonGames,0)'
    if s.count(anchor)!=1 or s.count(metric)!=1 or '  playerModal.showModal();' not in s:
        raise RuntimeError('Player layout changed; no files overwritten. Review the index integration.')
    s=s.replace(anchor,helper+anchor,1)
    s=s.replace(metric,metric+',\n    `<div class="miniCard lastThreeCard"><h4>3 המשחקים האחרונים</h4><p class="muted">טוען משחקים…</p></div>`',1)
    s=s.replace('  playerModal.showModal();','  const lastThreeCard=document.querySelector("#modalBody .lastThreeCard");\n  if(lastThreeCard)void fillLastThreeGames(name,lastThreeCard);\n  playerModal.showModal();',1)
    s=s.replace('</head>','<style>'+css+'</style></head>',1)
if 'data-tab="learning"' not in s:
    if '<nav class="tabs">' not in s or '</main>' not in s:raise RuntimeError('Tabs layout not recognized')
    start=s.index('<nav class="tabs">');end=s.index('</nav>',start)
    s=s[:end]+'<button data-tab="learning">למידה ובדיקת תחזיות</button>\n'+s[end:]
    section='<section id="learning" class="tab"><div class="card"><h2>למידה ובדיקת תחזיות</h2><p class="muted">השוואה לתוצאות בפועל ותיקונים שעוברים בדיקה על משחקים מאוחרים יותר.</p><div id="learningReport"></div></div></section>\n'
    s=s.replace('</main>',section+'</main>',1)
if 'href="./learning.css"' not in s:s=s.replace('</head>','<link rel="stylesheet" href="./learning.css"></head>',1)
if 'src="./learning.js"' not in s:s=s.replace('</body>','<script src="./learning-model-version.js"></script><script src="./learning.js"></script></body>',1)
p.write_text(s)
